In [3]:
import pandas as pd

In [4]:


# 1. Forcer l'affichage de TOUTES les lignes (pas de coupure au milieu)
pd.set_option('display.max_rows', None)

# 2. Forcer l'affichage de TOUTES les colonnes
pd.set_option('display.max_columns', None)

# 3. Forcer l'affichage de tout le texte sans le tronquer (ex: les longs noms de pôles)
pd.set_option('display.max_colwidth', None)

In [5]:
traitement = pd.read_csv("/home/onyxia/stage_2A/data/traitement_clean.csv")

In [6]:
print("--- Répartition des années d'obtention du FEDER ---")
print(traitement['annee'].value_counts().sort_index())

--- Répartition des années d'obtention du FEDER ---
annee
2007      762
2008     3454
2009    10025
2010    11010
2011     8571
2012     6266
2013     4504
2014     2085
2015      492
Name: count, dtype: int64

In [7]:
controls = pd.read_csv("/home/onyxia/stage_2A/api_geo_checkpoint.csv")

In [8]:
merge4_filtre=pd.read_csv("/home/onyxia/stage_2A/merge4_filtre.csv")

In [9]:
controls_clean = pd.merge(
    merge4_filtre, 
    controls, 
    left_on='bvdid', 
    right_on='siren_clean', 
    how='inner'
)

In [10]:
controls_clean.head()

,bvdid,country_code,consolidation_code,filing_type,closing_date,number_of_months,original_units,original_currency,exchange_rate_from_original_currency,total_assets,number_of_employees,operating_revenue_turnover,sales,name,entity_type,status,status_date,standardised_legal_form,national_legal_form,date_of_incorporation,type_of_entity,category_of_the_company,listed_delisted_unlisted,main_exchange,delisted_date,ipo_date,information_provider,bvd_major_sector,nace_rev_2_core_code_4_digits,isin_number,closing_datetime,year,siren_clean_x,siren_clean_y,departement,commune_insee
0,180036147,FR,C1,Annual report,20161231,12,thousands,EUR,1.0,987000000.0,2327.0,520800000.0,518900000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2016-12-31,2016,180036147,180036147,92,NaN
1,180036147,FR,C1,Annual report,20151231,12,thousands,EUR,1.0,859000000.0,2111.0,519400000.0,502400000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2015-12-31,2015,180036147,180036147,92,NaN
2,180036147,FR,C1,Annual report,20141231,12,thousands,EUR,1.0,597100000.0,2016.0,501900000.0,501900000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2014-12-31,2014,180036147,180036147,92,NaN
3,180036147,FR,C1,Annual report,20131231,12,thousands,EUR,1.0,567200000.0,1950.0,477200000.0,477200000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2013-12-31,2013,180036147,180036147,92,NaN
4,180036147,FR,C1,Annual report,20121231,12,thousands,EUR,1.0,506100000.0,1887.0,465700000.0,465700000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2012-12-31,2012,180036147,180036147,92,NaN

In [11]:
traitement.head()

,nom_beneficiaire,libelle_projet,cout_total,montant_feder,fonds_europeen,localisation,commune_beneficiaire,code_departement,annee,programme_europeen,thematique,siren,bvdid,country_code,consolidation_code,filing_type,closing_date,number_of_months,original_units,original_currency,exchange_rate_from_original_currency,total_assets,number_of_employees,operating_revenue_turnover,sales,status,status_date,standardised_legal_form,national_legal_form,date_of_incorporation,type_of_entity,category_of_the_company,listed_delisted_unlisted,main_exchange,delisted_date,ipo_date,information_provider,name,entity_type,closing_datetime,year,temps_relatif,post,bvd_major_sector,nace_rev_2_core_code_4_digits
0,agrivalor énergie,Création d'une unité de méthanisation sur l'exploitation agricole SCEA Ferme de l'Hirondelle,6317857.00,500000.00,FEDER,ALSACE / HAUT-RHIN / RIBEAUVILLE / RIBEAUVILLE / RIBEAUVILLE,HIRSINGUE,68,2009,Programme Régional FEDER ALSACE,01.04.41~Énergies renouvelables : énergie biomasse,498552652,498552652,FR,U1,Local registry filing,20141231,12,units,EUR,1.0,7902199.0,NaN,2939726.0,2869425.0,Active,NaN,Private limited companies,"Limited company, simplified - SAS",200706.0,Corporate,Medium sized company,Unlisted,Unlisted,NaN,NaN,Ellisphere,AGRIVALOR ENERGIE,C,2014-12-31,2014,5,1,"Machinery, equipment, furniture, recycling",3832
1,agrivalor énergie,Création d'une unité de méthanisation sur l'exploitation agricole SCEA Ferme de l'Hirondelle,6317857.00,500000.00,FEDER,ALSACE / HAUT-RHIN / RIBEAUVILLE / RIBEAUVILLE / RIBEAUVILLE,HIRSINGUE,68,2009,Programme Régional FEDER ALSACE,01.04.41~Énergies renouvelables : énergie biomasse,498552652,498552652,FR,U1,Local registry filing,20131231,12,units,EUR,1.0,9199103.0,NaN,2674959.0,2638797.0,Active,NaN,Private limited companies,"Limited company, simplified - SAS",200706.0,Corporate,Medium sized company,Unlisted,Unlisted,NaN,NaN,Ellisphere,AGRIVALOR ENERGIE,C,2013-12-31,2013,4,1,"Machinery, equipment, furniture, recycling",3832
2,agrivalor énergie,Création d'une unité de méthanisation sur l'exploitation agricole SCEA Ferme de l'Hirondelle,6317857.00,500000.00,FEDER,ALSACE / HAUT-RHIN / RIBEAUVILLE / RIBEAUVILLE / RIBEAUVILLE,HIRSINGUE,68,2009,Programme Régional FEDER ALSACE,01.04.41~Énergies renouvelables : énergie biomasse,498552652,498552652,FR,U1,Local registry filing,20121231,12,units,EUR,1.0,9768817.0,NaN,2242426.0,2227619.0,Active,NaN,Private limited companies,"Limited company, simplified - SAS",200706.0,Corporate,Medium sized company,Unlisted,Unlisted,NaN,NaN,Ellisphere,AGRIVALOR ENERGIE,C,2012-12-31,2012,3,1,"Machinery, equipment, furniture, recycling",3832
3,agrivalor énergie,Création d'une unité de méthanisation sur l'exploitation agricole SCEA Ferme de l'Hirondelle,6317857.00,500000.00,FEDER,ALSACE / HAUT-RHIN / RIBEAUVILLE / RIBEAUVILLE / RIBEAUVILLE,HIRSINGUE,68,2009,Programme Régional FEDER ALSACE,01.04.41~Énergies renouvelables : énergie biomasse,498552652,498552652,FR,U1,Local registry filing,20111231,12,units,EUR,1.0,NaN,NaN,900000.0,900000.0,Active,NaN,Private limited companies,"Limited company, simplified - SAS",200706.0,Corporate,Medium sized company,Unlisted,Unlisted,NaN,NaN,Ellisphere,AGRIVALOR ENERGIE,C,2011-12-31,2011,2,1,"Machinery, equipment, furniture, recycling",3832
4,almetis,Développement de molécules anticancéreuses de type organométalliques,114748.52,8420.37,FEDER,ALSACE / BAS-RHIN / STRASBOURG-VILLE / STRASBOURG / STRASBOURG,STRASBOURG,67,2011,Programme Régional FEDER ALSACE,"01.01.04~Aide à la RDT, notamment dans les PME (y compris accès aux services de RDT dans les centres de recherche)",529259095,529259095,FR,U1,Local registry filing,20131231,12,units,EUR,1.0,56540.0,NaN,-6940.0,0.0,Dissolved (bankruptcy),201504.0,Private limited companies,"Limited company, simplified - SAS",201012.0,Corporate,Small company,Unlisted,Unlisted,NaN,NaN,Ellisphere,NaN,NaN,2013-12-31,2013,2,1,Other services,7211

In [ ]:
print("--- Années de bilans disponibles pour les TRAITÉS ---")
print(traitement['year'].value_counts().sort_index().head(20))

print("\n--- Années de bilans disponibles pour les CONTRÔLES ---")
print(controls_clean['year'].value_counts().sort_index().head(20))

--- Années de bilans disponibles pour les TRAITÉS ---
year
1986       2
1987       2
1988       2
1989       3
1990       3
1991       3
1992       9
1993       9
1994      10
1995     672
1996    1044
1997    1125
1998    1290
1999    1358
2000    1437
2001    1566
2002    1674
2003    1876
2004    2024
2005    2134
Name: count, dtype: int64

--- Années de bilans disponibles pour les CONTRÔLES ---
year
2002    309784
2003    354147
2004    387657
2005    424388
2006    467566
2007    512468
2008    560226
2009    595870
2010    632566
2011    659802
2012    679649
2013    660056
2014    547244
2015    474154
2016    369093
2017     93958
2018        87
Name: count, dtype: int64

In [12]:
print("--- Répartition des années d'obtention du FEDER ---")
print(traitement['annee'].value_counts().sort_index())

--- Répartition des années d'obtention du FEDER ---
annee
2007      762
2008     3454
2009    10025
2010    11010
2011     8571
2012     6266
2013     4504
2014     2085
2015      492
Name: count, dtype: int64

In [13]:
treated = (
    traitement[
        ["bvdid", "annee"]
    ]
    .drop_duplicates()
    .rename(columns={"annee": "cohort"})
)

treated.head()

        bvdid  cohort
0   498552652    2009
4   529259095    2011
7   312868540    2013
29  799960034    2010
31  479230633    2014

In [14]:
nb = (
    treated
    .groupby("bvdid")
    .size()
)

print(nb.value_counts())

1    2076
2     250
3      90
4      42
5      20
6       4
7       3
8       1
Name: count, dtype: int64

In [15]:
# Nombre d'années FEDER différentes par entreprise
test = (
    traitement
    .groupby("bvdid")["annee"]
    .nunique()
)

print(test.value_counts().sort_index())

annee
1    2076
2     250
3      90
4      42
5      20
6       4
7       3
8       1
Name: count, dtype: int64

In [19]:
traitement.columns

Index(['nom_beneficiaire', 'libelle_projet', 'cout_total', 'montant_feder',
       'fonds_europeen', 'localisation', 'commune_beneficiaire',
       'code_departement', 'annee', 'programme_europeen', 'thematique',
       'siren', 'bvdid', 'country_code', 'consolidation_code', 'filing_type',
       'closing_date', 'number_of_months', 'original_units',
       'original_currency', 'exchange_rate_from_original_currency',
       'total_assets', 'number_of_employees', 'operating_revenue_turnover',
       'sales', 'status', 'status_date', 'standardised_legal_form',
       'national_legal_form', 'date_of_incorporation', 'type_of_entity',
       'category_of_the_company', 'listed_delisted_unlisted', 'main_exchange',
       'delisted_date', 'ipo_date', 'information_provider', 'name',
       'entity_type', 'closing_datetime', 'year', 'temps_relatif', 'post',
       'bvd_major_sector', 'nace_rev_2_core_code_4_digits'],
      dtype='object')

on ne garde qu'une année par subvention

In [ ]:
treated = (
    traitement
    .groupby("bvdid", as_index=False)
    .agg(
        cohort=("annee", "min")
    )
)

treated.head()

1    2486
Name: count, dtype: int64

préparation du panel

In [24]:
controls_clean.head()

,bvdid,country_code,consolidation_code,filing_type,closing_date,number_of_months,original_units,original_currency,exchange_rate_from_original_currency,total_assets,number_of_employees,operating_revenue_turnover,sales,name,entity_type,status,status_date,standardised_legal_form,national_legal_form,date_of_incorporation,type_of_entity,category_of_the_company,listed_delisted_unlisted,main_exchange,delisted_date,ipo_date,information_provider,bvd_major_sector,nace_rev_2_core_code_4_digits,isin_number,closing_datetime,year,siren_clean_x,siren_clean_y,departement,commune_insee
0,180036147,FR,C1,Annual report,20161231,12,thousands,EUR,1.0,987000000.0,2327.0,520800000.0,518900000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2016-12-31,2016,180036147,180036147,92,NaN
1,180036147,FR,C1,Annual report,20151231,12,thousands,EUR,1.0,859000000.0,2111.0,519400000.0,502400000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2015-12-31,2015,180036147,180036147,92,NaN
2,180036147,FR,C1,Annual report,20141231,12,thousands,EUR,1.0,597100000.0,2016.0,501900000.0,501900000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2014-12-31,2014,180036147,180036147,92,NaN
3,180036147,FR,C1,Annual report,20131231,12,thousands,EUR,1.0,567200000.0,1950.0,477200000.0,477200000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2013-12-31,2013,180036147,180036147,92,NaN
4,180036147,FR,C1,Annual report,20121231,12,thousands,EUR,1.0,506100000.0,1887.0,465700000.0,465700000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2012-12-31,2012,180036147,180036147,92,NaN

In [36]:
panel = controls_clean[
    [
        "bvdid",
        "year",
        "sales",
        "total_assets",
        "number_of_employees",
        "date_of_incorporation",
        "bvd_major_sector",
        "standardised_legal_form",
        "category_of_the_company",
        "departement", 
        "consolidation_code"
    ]
].copy()

traitement des doublons

In [37]:
dup = (
    panel
    .duplicated(subset=["bvdid", "year"])
)

print("Nombre de doublons :", dup.sum())

Nombre de doublons : 31915

In [30]:
doublons = controls_clean[
    controls_clean.duplicated(subset=["bvdid", "year"], keep=False)
].sort_values(["bvdid", "year"])

doublons.head(20)

,bvdid,country_code,consolidation_code,filing_type,closing_date,number_of_months,original_units,original_currency,exchange_rate_from_original_currency,total_assets,number_of_employees,operating_revenue_turnover,sales,name,entity_type,status,status_date,standardised_legal_form,national_legal_form,date_of_incorporation,type_of_entity,category_of_the_company,listed_delisted_unlisted,main_exchange,delisted_date,ipo_date,information_provider,bvd_major_sector,nace_rev_2_core_code_4_digits,isin_number,closing_datetime,year,siren_clean_x,siren_clean_y,departement,commune_insee
16,180036147,FR,C2,Local registry filing,20071231,12,units,EUR,1.0,334147000.0,NaN,0.0,322661000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2007-12-31,2007,180036147,180036147,92,NaN
26,180036147,FR,U2,Local registry filing,20071231,12,thousands,EUR,1.0,278964074.0,NaN,26617090.0,15970049.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2007-12-31,2007,180036147,180036147,92,NaN
15,180036147,FR,C2,Local registry filing,20081231,12,units,EUR,1.0,379889000.0,NaN,0.0,352436000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2008-12-31,2008,180036147,180036147,92,NaN
25,180036147,FR,U2,Local registry filing,20081231,12,thousands,EUR,1.0,280957775.0,41.0,30519589.0,19446649.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2008-12-31,2008,180036147,180036147,92,NaN
14,180036147,FR,C2,Local registry filing,20091231,12,units,EUR,1.0,420094000.0,NaN,382715000.0,375671000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2009-12-31,2009,180036147,180036147,92,NaN
24,180036147,FR,U2,Local registry filing,20091231,12,thousands,EUR,1.0,262965765.0,40.0,35314402.0,24646432.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2009-12-31,2009,180036147,180036147,92,NaN
6,180036147,FR,C1,Annual report,20101231,12,thousands,EUR,1.0,445265000.0,1835.0,416800000.0,411635000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2010-12-31,2010,180036147,180036147,92,NaN
13,180036147,FR,C2,Local registry filing,20101231,12,units,EUR,1.0,445265000.0,NaN,411635000.0,411635000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2010-12-31,2010,180036147,180036147,92,NaN
23,180036147,FR,U2,Local registry filing,20101231,12,thousands,EUR,1.0,299413944.0,28.0,39509330.0,27186987.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2010-12-31,2010,180036147,180036147,92,NaN
5,180036147,FR,C1,Annual report,20111231,12,thousands,EUR,1.0,500588000.0,1931.0,437269000.0,432418000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2011-12-31,2011,180036147,180036147,92,NaN
12,180036147,FR,C2,Local registry filing,20111231,12,units,EUR,1.0,500588000.0,NaN,432418000.0,432418000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2011-12-31,2011,180036147,180036147,92,NaN
22,180036147,FR,U2,Local registry filing,20111231,12,thousands,EUR,1.0,335939156.0,24.0,36869694.0,24597390.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2011-12-31,2011,180036147,180036147,92,NaN
4,180036147,FR,C1,Annual report,20121231,12,thousands,EUR,1.0,506100000.0,1887.0,465700000.0,465700000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2012-12-31,2012,180036147,180036147,92,NaN
11,180036147,FR,C2,Local registry filing,20121231,12,units,EUR,1.0,506097000.0,NaN,465701000.0,465701000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2012-12-31,2012,180036147,180036147,92,NaN
21,180036147,FR,U2,Local registry filing,20121231,12,thousands,EUR,1.0,435934179.0,25.0,40583675.0,28323823.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2012-12-31,2012,180036147,180036147,92,NaN
3,180036147,FR,C1,Annual report,20131231,12,thousands,EUR,1.0,567200000.0,1950.0,477200000.0,477200000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2013-12-31,2013,180036147,180036147,92,NaN
10,180036147,FR,C2,Local registry filing,20131231,12,units,EUR,1.0,567200000.0,1950.0,477176000.0,477176000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2013-12-31,2013,180036147,180036147,92,NaN
20,180036147,FR,U2,Local registry filing,20131231,12,thousands,EUR,1.0,567312932.0,NaN,68077679.0,32047328.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2013-12-31,2013,180036147,180036147,92,NaN
2,180036147,FR,C1,Annual report,20141231,12,thousands,EUR,1.0,597100000.0,2016.0,501900000.0,501900000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2014-12-31,2014,180036147,180036147,92,NaN
9,180036147,FR,C2,Local registry filing,20141231,12,units,EUR,1.0,597130000.0,2016.0,501856000.0,501856000.0,LABORATOIRE FRANCAIS DU FRACTIONNEMENT ET DES BIOTECHNOLOGIES,C,Active,NaN,Public limited companies,Limited company - SA,199406.0,Corporate,Very large company,Unlisted,Unlisted,NaN,NaN,Ellisphere,"Chemicals, rubber, plastics, non-metallic products",2120.0,NaN,2014-12-31,2014,180036147,180036147,92,NaN

In [32]:
controls_clean["consolidation_code"].value_counts()

consolidation_code
U1    3211859
U2      35867
C2      20146
C1       4893
Name: count, dtype: int64

In [34]:
pd.crosstab(
    controls_clean["consolidation_code"],
    controls_clean["filing_type"]
)

filing_type         Annual report  Local registry filing
consolidation_code
C1                           4887                      6
C2                            191                  19955
U1                            162                3211697
U2                             86                  35781

On va suivre la logique d'Orbis :

si une entreprise n'a qu'un seul compte → on le garde ;
si plusieurs types de comptes existent pour une même année → on choisit le meilleur disponible.

In [ ]:
treated_ids = set(treated["bvdid"])

controls = controls[
    ~controls["bvdid"].isin(treated_ids)
].copy()

In [38]:
priorite = {
    "C1": 1,
    "C2": 2,
    "U1": 3,
    "U2": 4
}

panel["priority"] = panel["consolidation_code"].map(priorite)

panel = (
    panel
    .sort_values(["bvdid", "year", "priority"])
    .drop_duplicates(subset=["bvdid", "year"], keep="first")
    .drop(columns="priority")
)

In [39]:
panel.duplicated(["bvdid", "year"]).sum()

np.int64(0)

In [40]:
treated_ids = set(traitement["bvdid"])

len(treated_ids)

2486

In [41]:
control_ids = set(panel["bvdid"])

len(control_ids)

248177

In [42]:
len(treated_ids & control_ids)

744

In [43]:
treated_ids = set(traitement["bvdid"])

controls_clean = panel[
    ~panel["bvdid"].isin(treated_ids)
].copy()

In [44]:
len(set(controls_clean["bvdid"]) & treated_ids)

0

In [46]:
traitement_panel = traitement.copy()

traitement_panel["priority"] = (
    traitement_panel["consolidation_code"]
    .map(priorite)
)

traitement_panel = (
    traitement_panel
    .sort_values(
        ["bvdid","year","priority"]
    )
    .drop_duplicates(
        ["bvdid","year"]
    )
    .drop(columns="priority")
)

In [47]:
traitement_panel.duplicated(
    ["bvdid","year"]
).sum()

np.int64(0)

In [ ]:
traitement_panel = traitement_panel.merge(
    treated,
    on="bvdid"
)